package zimage

// Code generated by SdkContractGenerator. DO NOT EDIT.

var contractSchema = map[string]any{"text-to-image": map[string]any{"models": []any{"z-image"}, "fields_by_model": map[string]any{"z-image": map[string]any{"aspect_ratio": map[string]any{"enum": []any{"1:1", "4:3", "3:4", "16:9", "9:16"}, "required": true}, "prompt": map[string]any{"required": true, "min": 1, "max": 1000, "length": true}}}}}
