package ai.runapi.core.pricing;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
/** A runtime-owned public price schedule entry. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class PriceSchedule {
  @JsonProperty("service") private String service; @JsonProperty("action") private String action; @JsonProperty("model") private String model;
  @JsonProperty("pricing_status") private String pricingStatus; @JsonProperty("catalog_status") private String catalogStatus; @JsonProperty("currency") private String currency; @JsonProperty("billing_unit") private String billingUnit; @JsonProperty("billing_strategy") private String billingStrategy; @JsonProperty("unit_price_cents") private Long unitPriceCents; @JsonProperty("input_price_per_1m_cents") private Long inputPricePer1mCents; @JsonProperty("output_price_per_1m_cents") private Long outputPricePer1mCents; @JsonProperty("cache_read_price_per_1m_cents") private Long cacheReadPricePer1mCents; @JsonProperty("cache_write_price_per_1m_cents") private Long cacheWritePricePer1mCents; @JsonProperty("cache_write_5m_price_per_1m_cents") private Long cacheWrite5mPricePer1mCents; @JsonProperty("cache_write_1h_price_per_1m_cents") private Long cacheWrite1hPricePer1mCents; @JsonProperty("billing_config") private JsonNode billingConfig;
  public String getService() { return service; } public String getAction() { return action; } public String getModel() { return model; } public String getPricingStatus() { return pricingStatus; } public String getCatalogStatus() { return catalogStatus; } public String getCurrency() { return currency; } public String getBillingUnit() { return billingUnit; } public String getBillingStrategy() { return billingStrategy; } public Long getUnitPriceCents() { return unitPriceCents; } public Long getInputPricePer1mCents() { return inputPricePer1mCents; } public Long getOutputPricePer1mCents() { return outputPricePer1mCents; } public Long getCacheReadPricePer1mCents() { return cacheReadPricePer1mCents; } public Long getCacheWritePricePer1mCents() { return cacheWritePricePer1mCents; } public Long getCacheWrite5mPricePer1mCents() { return cacheWrite5mPricePer1mCents; } public Long getCacheWrite1hPricePer1mCents() { return cacheWrite1hPricePer1mCents; } public JsonNode getBillingConfig() { return billingConfig; }
}
